#posts account data

curl -H "Content-Type: application/json" -X POST -d '{"balance": "1000", "name": "savings"}' "http://localhost:3000/accounts"

# gets account data
curl "http://localhost:3000/accounts/5a36706b5138112c26033b85"

#updates account data at specific id, NOTE: replace 'id' in "http://localhost:3000/accounts/id" with the id generated by the previous POST command

curl -H "Content-Type: application/json" -X PUT -d '{"balance": "3500"}' "http://localhost:3000/accounts/5a36706b5138112c26033b85"

#//deletes account data at specific id, NOTE: replace 'id' in "http://localhost:3000/accounts/id" with the id generated by the previous POST command

curl -X DELETE "http://localhost:3000/accounts/5a36706b5138112c26033b85"